### ISSUE TITLE
Add custom module template selection

### ISSUE THREAD

**Issue by agoat** [terminal42/contao-changelanguage#143] opened 2017-12-01 15:18 UTC
All core modules have a Template setting to select a **'Custom module template'**. 
I miss this in the changelanguage module.

**Comment by Toflar** [comment] 2017-12-04 08:28
Duplicate of https://github.com/terminal42/contao-changelanguage/issues/141

**Closed by Toflar** 2017-12-04 08:28 UTC

**Comment by agoat** [comment] 2017-12-04 08:36
Oh, I wonder why I didn't see that?!
