### ISSUE TITLE
Link "showOnSelect" in backend.

### ISSUE THREAD

**Issue by stefanschleich** [terminal42/contao-changelanguage#77] opened 2016-09-07 08:45 UTC
Since the update to version 3.0.1 (updated through the Extension Manager) I see a link with the text "showOnSelect" after "Neues Element" in the backend which I suppose shouldn't be there:

![Link](https://cloud.githubusercontent.com/assets/1949608/18305442/e399e6b6-74e7-11e6-8957-299fdc7f2ed7.png)

This link is also visible in the site structure after "Neue Seite":

![fehler-changelanguage-seite](https://cloud.githubusercontent.com/assets/1949608/18305503/27460502-74e8-11e6-9147-730ea492fdb1.png)

I'm using Contao 3.5.14.

**Comment by aschempp** [comment] 2016-09-26 06:12
does that text disappear if you disable the changelanguage extension? Because I don't see a reason for this to happen…

**Comment by Toflar** [comment] 2016-09-26 07:45
Internal cached?

**Comment by stefanschleich** [comment] 2016-09-28 08:56
It does disappear if I disable the extension and it doesn't matter if I clear the internal cache.

**Comment by sceadara** [comment] 2016-09-28 09:16
I can see this "showOnSelect" Link too. 
After a little 5min research, I found just one line with the "showOnSelect". Badly, I can't say what it does there, but I just deleted the line to test and everything looks and i think works still fine.
So it's just an idea. Correct me if I'm wrong.

https://github.com/terminal42/contao-changelanguage/blob/ad4269ece6918109cc4361bb4bf46a7fa9441ed7/library/Terminal42/ChangeLanguage/EventListener/BackendView/AbstractViewListener.php#L82

atm this is a Contao 3.5.8

**Comment by Toflar** [comment] 2016-09-28 09:28
This line is needed because it shows the button when in select mode. It has been introduced here: https://github.com/contao/core/commit/da885ca8682746ddba27e281caac6329f9a931b9. You need at least Contao 3.5.5 for that (but minimum for changelanguage is 3.5.8 anyway).

**Comment by sceadara** [comment] 2016-09-28 09:46
Ah ok i c. Not tested with select mode. My fault, sorry :)

**Comment by Toflar** [comment] 2016-09-28 09:47
But still, can you try to debug why it is part of your label? I cannot reproduce it.

**Comment by sceadara** [comment] 2016-09-28 10:00
yapp i investigate this.
fyi i upgraded to Contao Version 3.5.17 and it's still there

**Comment by sceadara** [comment] 2016-09-28 11:14
i just put the "showOnSelect => true," inside the "switchLanguage"-Array. Thats all?

As far as i understand this, you add "2 arrays" to the labels. one is "showOnSelect" and the other is your language switch "switchLanguage". The switch should contain the option "showOnSelect"

right  ?

**Comment by aschempp** [comment] 2016-10-06 08:14
Fixed in da01711db112f584f701b9b67deacdc15d1d46b7

**Closed by aschempp** 2016-10-06 08:14 UTC
Labels: bug
