### ISSUE TITLE
Backend custom language text not loading

### ISSUE THREAD

**Issue by christianromeni** [terminal42/contao-changelanguage#138] opened 2017-09-28 20:38 UTC
When checking the Custom Language Checkbox, nothing appears:
![image](https://user-images.githubusercontent.com/1358040/30989359-b9c50230-a49d-11e7-921a-f1665df6e442.png)
Even after saving and opening the module again.
The part in the source code is empty:
![image](https://user-images.githubusercontent.com/1358040/30989398-daba08c8-a49d-11e7-9a33-71ee978150d9.png)

**Comment by aschempp** [comment] 2017-09-28 21:24
Duplicate of #124

**Closed by aschempp** 2017-09-28 21:24 UTC
