### ISSUE TITLE
Query Parameter - Multiple-Selects ,Multiple-Checkboxes

### ISSUE THREAD

**Issue by isdgroup** [terminal42/contao-changelanguage#177] opened 2020-05-05 08:42 UTC
Hi,

maybe it is a bug or maybe it is not possible.

Wheren you have a GET-Form on the Page with Form with a Multiple-Select / Multiple Checkboxes, than the Browser-URL looks like this:
example.org/de/test.html?category[]=1,2,3

if you then take a look at the link of the language changer the URL looks like this:

example.org/en/test.html?category[]=Array

The Parameter in the Contao Backend is set to
category

Is it possible to change that / make it possible ?

I am not quite sure if its a bug, or if i do a misstake by myself.

**Comment by aschempp** [comment] 2020-05-06 05:44
I don‘t think the language switch was intended to switch GET forms, but passing `Array` is certainly a bug to me 🙃

**Comment by aschempp** [comment] 2020-07-28 06:07
Fixed in 295cf394224323ef6718a67368ad3d22ccdb6843

**Closed by aschempp** 2020-07-28 06:07 UTC
Labels: bug
