### ISSUE TITLE
Installtool error

### ISSUE THREAD

**Issue by Ernestopheles** [terminal42/contao-changelanguage#203] opened 2021-08-29 08:42 UTC
Sprachenwechsler been running fine under contao 4.11 in version 3.2.1. After updating 4.12 and 3.2.2 installtool error
`In ParameterBag.php line 93:
 You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"?`

Deinstalling Sprachenwechsler and new install with 3.2.1 did not help.

**Comment by fritzmg** [comment] 2021-08-29 08:47
Possibly duplicate of #197

**Closed** 2021-08-29 13:37 UTC
