### ISSUE TITLE
Cannot deactivate calendar (and probably news and faq modules)

### ISSUE THREAD

**Issue by Toflar** [terminal42/contao-changelanguage#82] opened 2016-10-06 11:34 UTC
When doing so, you get a `Fatal error: Uncaught exception InvalidArgumentException with message (Sub)palette "default" not found in table "tl_calendar" thrown in composer/vendor/codefog/contao-haste/library/Haste/Dca/PaletteManipulator.php on line 211` when trying to update the database because the palette does not exist.

**Comment by aschempp** [comment] 2016-11-23 10:36
I cannot reproduce this issue. Did you use the Extension Repository to update the database?

**Comment by Toflar** [comment] 2016-11-23 10:48
Cannot reproduce it either anymore. Strange. I close.

**Comment by Toflar** [comment] 2016-11-23 12:00
Just reproduced the issue again by just updating changelanguage. Not sure what causes the issue though but I guess we should just add a try-catch block to be sure.

**Comment by sheeep** [comment] 2016-12-14 16:11
I'm able to reproduce this as well. So far, I found the following actions affected by this:

* deleting a page
* updating the database schema

PR #95 seems to fix this issue.

**Comment by aschempp** [comment] 2016-12-15 11:23
If you can reproduce it, can you figure out why the events are registered at all? That should only happen if a DCA table is loaded with given name?

**Comment by aschempp** [comment] 2017-02-02 09:00
Should be fixed in b3843691833e045440eb7d95b60db54218209eed

**Closed by aschempp** 2017-02-02 09:00 UTC
Labels: bug
