### ISSUE TITLE
Cannot choose main language page on new record

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-changelanguage#132] opened 2017-08-06 08:10 UTC
* Contao 4.4.2
* Changelanguage 3.1.6

## Reproduction

1. Create a website root for language `en` and set as fallback.
2. Create a new page within the `en` website root called `Start page` with the alias `index`.
3. Create a website root for language `de`.
4. Create a new page within the `de` website root called `Startseite` with the alias `index` and choose the pendant page `Start page` under __Main language page__.
5. Save.

The error
```
Cannot load record "tl_page.id=XX"
```
will occur, where XX would be the ID of the newly created page record.

![screen shot 2017-08-06 at 10 06 03](https://user-images.githubusercontent.com/4970961/29001613-3c8f66d0-7a8f-11e7-97e6-a2b0b4d441a9.png)

## Workaround

Currently you have to:

1. Create a new page and _don't_ set a __Main language page__.
2. Save.
3. Now the __Main language page__ setting will work.

See also https://community.contao.org/de/showthread.php?67464-Keine-Seite-in-Hauptsprache-auswählbar

**Comment by aschempp** [comment] 2017-08-13 10:55
I can't reproduce this or I don't understand. How can you select a page in the fallback language, according to your reproduction steps you did not create any?

**Comment by fritzmg** [comment] 2017-08-13 12:13
That's step 1.

**Comment by fritzmg** [comment] 2017-08-14 12:19
Could this be a limitation of the new dcaPicker? Usually, if you create a new page record, don't save it and then go back to the list view, Contao will automatically delete any unfinished records. It appears the same is happening now if you open a `pageTree` from within a `page` record.

**Comment by fritzmg** [comment] 2017-08-14 12:28
Yes, this is exactly what happens. When you open a `pageTree` modal window, the `Contao\DC_Tabe::showAll` function will call `Contao\DC_Table::reviseTable` and this function will delete any unfinished records: https://github.com/contao/core-bundle/blob/4.4.2/src/Resources/contao/drivers/DC_Table.php#L3317-L3331

**Comment by aschempp** [comment] 2017-09-21 20:05
Can you confirm this still happens in the latest version and latest Contao (picker rewrite)?

**Comment by fritzmg** [comment] 2017-09-21 20:52
Yes, this still happens in Contao 4.4.5.

**Comment by mpitz** [comment] 2017-09-22 13:54
I can also confirm this behavior.

**Comment by christianromeni** [comment] 2017-09-28 20:15
I can confirm, same happened right now with the latest version.
![image](https://user-images.githubusercontent.com/1358040/30988358-80b41894-a49a-11e7-9b27-c43a341bd6f1.png)
It looks like after selecting the page in the picker, it is not selected:
![image](https://user-images.githubusercontent.com/1358040/30988390-96b933f4-a49a-11e7-9c73-d6ddc6bebab7.png)

**Comment by Toflar** [comment] 2017-11-14 08:55
Closing this issue because it's a picker issue and cannot be solved by Changelanguage.

**Closed by Toflar** 2017-11-14 08:55 UTC
